Asp.net MVC MVC 4 Integration/MvcOSGi.Shell/Plugins/BlogPlugin/Models/Movies.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BlogPlugin.Models
{
    public class Movies
    {
        private static List<Movie> _movies;
        static Movies()
        {
            _movies = new List<Movie>();
            _movies.Add(new Movie() { Name = "M1", Rating = 5 });
            _movies.Add(new Movie() { Name = "M2", Rating = 5 });
        }

        public List<Movie> GetMovies()
        {
            return _movies;
        }
    }

    public class Movie
    {
        public string Name { get; set; }
        public int Rating { get; set; }
    }
}

Asp.net MVC MVC 4 Integration/MvcOSGi.Shell/Plugins/BlogPlugin/Controllers/BlogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BlogPlugin.Controllers
{
    public class BlogController : Controller
    {
        //
        // GET: /Blog/

        public ActionResult Index()
        {
            ViewBag.Title = "Blog";
            return View();
        }

        //
        // GET: /Blog/Details/5

        public ActionResult Details(int id)
        {
            return View();
        }

        //
        // GET: /Blog/Create

        public ActionResult Create()
        {
            return View();
        } 

        //
        // POST: /Blog/Create

        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
        
        //
        // GET: /Blog/Edit/5
 
        public ActionResult Edit(int id)
        {
            return View();
        }

        //
        // POST: /Blog/Edit/5

        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here
 
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Blog/Delete/5
 
        public ActionResult Delete(int id)
        {
            return View();
        }

        //
        // POST: /Blog/Delete/5

        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here
 
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Asp.net MVC MVC 4 Integration/MvcOSGi.Shell/Plugins/BlogPlugin/Controllers/HelloController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BlogPlugin.Models;

namespace BlogPlugin.Controllers
{
    public class HelloController : Controller
    {
        //
        // GET: /Hello/

        public ActionResult Index()
        {
            var model = new Movies();
            return View(model.GetMovies());
        }

        public ActionResult Other()
        {
            return View();
        }

    }
}

Asp.net MVC MVC 4 Integration/MvcOSGi.Shell/Plugins/BlogPlugin/Controllers/SupportController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BlogPlugin.Controllers
{
    public class SupportController : Controller
    {
        //
        // GET: /Support/

        public ActionResult Index()
        {
            return View();
        }

        //
        // GET: /Support/Details/5

        public ActionResult Details(int id)
        {
            return View();
        }

        //
        // GET: /Support/Create

        public ActionResult Create()
        {
            return View();
        } 

        //
        // POST: /Support/Create

        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
        
        //
        // GET: /Support/Edit/5
 
        public ActionResult Edit(int id)
        {
            return View();
        }

        //
        // POST: /Support/Edit/5

        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here
 
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Support/Delete/5
 
        public ActionResult Delete(int id)
        {
            return View();
        }

        //
        // POST: /Support/Delete/5

        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here
 
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Asp.net MVC MVC 4 Integration/MvcOSGi.Shell/Plugins/BlogPlugin/Views/Blog/Index.cshtml
@{
    ViewBag.Title = "Index";
}
<script type="text/javascript">
    PageId = 4;
</script>
<div class="article">
    <h2><span>A Blog</span> Entry</h2>
    <div class="clr"></div>
    <p>Posted by <a href="#">Owner</a> <span>&nbsp;&bull;&nbsp;</span> Filed under <a href="#">templates</a>, <a href="#">internet</a></p>
    <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Donec libero. Suspendisse bibendum. Cras id urna. Morbi tincidunt, orci ac convallis aliquam, lectus turpis varius lorem, eu posuere nunc justo tempus leo. Donec mattis, purus nec placerat bibendum, dui pede condimentum odio, ac blandit ante orci ut diam. Cras fringilla magna. Phasellus suscipit, leo a pharetra condimentum, lorem tellus eleifend magna, eget fringilla velit magna id neque. Curabitur vel urna. In tristique orci porttitor ipsum. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Donec libero. Suspendisse bibendum. Cras id urna. Morbi tincidunt, orci ac convallis aliquam, lectus turpis varius lorem, eu posuere nunc justo tempus leo. </p>
    <p>Tagged: <a href="#">orci</a>, <a href="#">lectus</a>, <a href="#">varius</a>, <a href="#">turpis</a></p>
    <p><a href="#"><strong>Comments (3)</strong></a> <span>&nbsp;&bull;&nbsp;</span> May 27, 2010 <span>&nbsp;&bull;&nbsp;</span> <a href="#"><strong>Edit</strong></a></p>
</div>
<div class="article">
    <h2><span>3</span> Responses</h2>
    <div class="clr"></div>
    <div class="comment"> <a href="#"><img src="images/userpic.gif" width="40" height="40" alt="" class="userpic" /></a>
        <p><a href="#">admin</a> Says:<br />
            April 20th, 2009 at 2:17 pm</p>
        <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Donec libero. Suspendisse bibendum.</p>
    </div>
    <div class="comment"> <a href="#"><img src="images/userpic.gif" width="40" height="40" alt="" class="userpic" /></a>
        <p><a href="#">Owner</a> Says:<br />
            April 20th, 2009 at 3:21 pm</p>
        <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Donec libero. Suspendisse bibendum. Cras id urna. Morbi tincidunt, orci ac convallis aliquam, lectus turpis varius lorem, eu posuere nunc justo tempus leo.</p>
    </div>
    <div class="comment"> <a href="#"><img src="images/userpic.gif" width="40" height="40" alt="" class="userpic" /></a>
        <p><a href="#">admin</a> Says:<br />
            April 20th, 2009 at 2:17 pm</p>
        <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Donec libero. Suspendisse bibendum.</p>
    </div>
</div>

Asp.net MVC MVC 4 Integration/MvcOSGi.Shell/Plugins/BlogPlugin/Views/Hello/Index.cshtml
@{
    ViewBag.Title = "Index";
}
@model List<BlogPlugin.Models.Movie>
<h2>Index in BlogPlugin</h2>

@Html.ActionLink("Other in BlogPlugin", "Other")
<br />
@Html.ActionLink("Hello2 in BlogPlugin", "Index", "Hello2", new { plugin = "BlogPlugin" }, null)
<br />
@Html.ActionLink("Hello2 in BlogPlugin", "Index", "Hello2")

<br />
<table>
    <tr>
        <td>Name</td>
        <td>Rating</td>
    </tr>
    @foreach (var movie in Model)
    {
        <tr>
            <td>@movie.Name</td>
            <td>@movie.Rating</td>
        </tr>
    }
</table>
<br />
<b>Click below link to brower movice list which is provided by another plugin>>></b>
<br />
@Html.ActionLink("Movice List", "Index", "Hello", new { plugin = "MovicePlugin" }, null)

Asp.net MVC MVC 4 Integration/MvcOSGi.Shell/Plugins/BlogPlugin/Views/Hello/Other.cshtml
@{
    ViewBag.Title = "Other";
}

<h2>Other in BlogPlugin</h2>

Asp.net MVC MVC 4 Integration/MvcOSGi.Shell/Plugins/BlogPlugin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Plugins/BlogPlugin/Content/Site.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Plugins/BlogPlugin/Scripts/jquery-1.5.1.min.js")" type="text/javascript"></script>
</head>

<body>
    @RenderBody()
</body>
</html>

Asp.net MVC MVC 4 Integration/MvcOSGi.Shell/Plugins/BlogPlugin/Views/Support/Index.cshtml
@{
    ViewBag.Title = "Support";
}
<script type="text/javascript">
    PageId = 2;
</script>
 <div class="article">
          <h2><span>Support to</span> Company Name</h2>
          <div class="clr"></div>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. <strong>Suspendisse nulla ligula, blandit ultricies aliquet ac, lobortis in massa. Nunc dolor sem, tincidunt vitae viverra in, egestas sed lacus.</strong> Etiam in ullamcorper felis. Nulla cursus feugiat leo, ut dictum metus semper a. Vivamus euismod, arcu gravida sollicitudin vestibulum, quam sem tempus quam, quis ullamcorper erat nunc in massa. Donec aliquet ante non diam sollicitudin quis auctor velit sodales. Morbi neque est, posuere at fringilla non, mollis nec nibh. Sed commodo tortor nec sem tincidunt mattis. Nam convallis aliquam nibh eu luctus. Nunc vel tincidunt lacus. Suspendisse sit amet pulvinar ante.</p>
          <p>Phasellus diam justo, laoreet vel vulputate eu, congue vel est. Maecenas eros libero, sollicitudin a vulputate fermentum, ultrices vel lacus. Nam in metus non augue fermentum consequat ultrices ac enim. Integer aliquam urna non diam aliquam eget hendrerit sem molestie.</p>
          <p><strong>Lorem ipsum dolor sit amet</strong></p>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum eget bibendum tellus. Nunc vel imperdiet tellus. Mauris ornare aliquam urna, accumsan bibendum eros auctor ac.</p>
          <ul class="sb_menu">
            <li><a href="#"><strong>Lorem ipsum</strong></a></li>
            <li><a href="#"><strong>Lorem ipsum</strong></a></li>
            <li><a href="#"><strong>Lorem ipsum</strong></a></li>
            <li><a href="#"><strong>Lorem ipsum</strong></a></li>
            <li><a href="#"><strong>Lorem ipsum</strong></a></li>
            <li><a href="#"><strong>Lorem ipsum</strong></a></li>
          </ul>
        </div>